// SentinelAI Environment Configuration Template
// For local testing, copy this file to config.js and add your API key.
// In GitHub Pages, this file is automatically generated via GitHub Actions secrets.

window.SENTINEL_CONFIG = {
  API_KEY: ''
};
